version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "80"
      
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: my-user
      MYSQL_DATABASE: my-db
      MYSQL_PASSWORD: my-password
